### ISSUE TITLE
Support of custom API name 

### ISSUE THREAD

**Issue by mohitkadel** [dvla/serverless-apigateway-log-retention#12]
Hi

Thanks for sharing your plugin!
I had a bit of trouble getting a custom API name other than `[STAGE]-[SERVICE_NAME]`. However, There is no option to set it up.
This requirement can be met with other developes as well.

**Comment by TobiaZambon** [comment]
This will be useful, I agree and hope will be implemented

**Comment by deepakthankachan** [comment]
I've left comments on the PR @mohitkadel

**Comment by deepakthankachan** [comment]
Will be fixed as part of [AWS SDK V3 upgrade PR](https://github.com/dvla/serverless-apigateway-log-retention/pull/14)
