### ISSUE TITLE
plugin failing to retrieve restApi Id under proxy settings 

### ISSUE THREAD

**Issue by samirkape** [dvla/serverless-apigateway-log-retention#6]
Hello,

Thank you for the awesome plugin!

We have been using it in production since last year and it worked well until we decided to migrate the pipeline under our organization's docker instances. As a side effect, the plugin can no longer retrieve the restApi Id and returns `connect ETIMEDOUT xx.xxx.85.247:443`

Is there any way we can provide a proxy config to the plugin?

**Comment by deepakthankachan** [comment]
Have left comments on your PR
